### PR TITLE
022 comparing input key

### PR DESCRIPTION
**Pull request by AniSanikidze**

### CODE REVIEW

**Review by adzai — CHANGES_REQUESTED** [review]
For future reference, create different PRs for different issues, here you have commits with data which should be tied to #10 as they have nothing to do with #22.

Regarding the function, you should change the "keyword" binding to a different name, as it is a [function in clojure](https://clojuredocs.org/clojure.core/keyword). And of course, the function should return the matching tag, not just print it. Otherwise fine.

**Comment by irinakulinich3712** [comment]
It's working fine, however, what we are aiming at is comparing the user input not to the list of main keywords, but to the vectors of synonyms (containing the main keywords as well). Thus, the comparison function will be more complicated. The aim of it, as I see it, is then to return the main keyword identifying the synonyms vector, in which the similarity has been found. That keyword will then be found in the data structure containing information about parks.

In addition, I think what we should do is keep the comparison function here separate from the main loop receiving user input. Just keep the comparison process and the comparison function will then have argument - for receiving the user input from the main loop

**Comment by irinakulinich3712** [comment]
> I would go one step at a time - first worry about getting the responses based on the main keywords right, then expand to synonyms.
> 
> > In addition, I think what we should do is keep the comparison function here separate from the main loop receiving user input. Just keep the comparison process and the comparison function will then have argument - for receiving the user input from the main loop
> 
> I don't quite understand what you mean by keeping it separate from the main loop. Surely it has to be called from the main loop?

Of course it should be in the main loop, but the comparison function itself is not about receiving user input directly, I think it should receive the parsed user input from the main function

**Comment by adzai** [comment]
Yea, I think Ani mentioned this was supposed to be just a working example. Would be better if you wrote what this is in the description @AniSanikidze 
But in the end, I think that parse-input should ideally handle everything and return a response sentence or the tag it chose.

**Comment by adzai** [comment]
Moved to #25

**Pull request closed without merging**
