### PR TITLE
061 cleanup

### PR DESCRIPTION
**Pull request by adzai**
Refactoring redundant comparisons and so on.

Changed find_park_data.clj to use generic park name.

Please double check the functionality, I just quickly skimmed through it 
and refactored obvious stuff. 

I might change more things later if we have time.

### CODE REVIEW

**Review by irinakulinich3712 — COMMENTED** [review]
Looks nice in general. So basically this updated structure of find-park-data implies we'll need to have a separate file per each park? But won't it be better to fetch the required values from the data-en.json, using the park name as key instead?

**Comment by adzai** [comment]
> Looks nice in general. So basically this updated structure of find-park-data implies we'll need to have a separate file per each park? But won't it be better to fetch the required values from the data-en.json, using the park name as key instead?

Added

**Comment by irinakulinich3712** [comment]
> > Looks nice in general. So basically this updated structure of find-park-data implies we'll need to have a separate file per each park? But won't it be better to fetch the required values from the data-en.json, using the park name as key instead?
> 
> Added

Yeah, I like it much better

**Review by irinakulinich3712 — DISMISSED** [review]

**Review by AniSanikidze — APPROVED** [review]
Looks really nice!

**Review by AniSanikidze — APPROVED** [review]

**Pull request merged**
