### PR TITLE
Allow the user to choose and change the park

### PR DESCRIPTION
**Pull request by adzai**
Let the user choose the park and change it later on. Same as they currently can with their username.

### CODE REVIEW

**Comment by adzai** [comment]
Also I put find_park_data into park_utils, since I think that makes more sense since that file now exists. What do you think?

**Comment by AniSanikidze** [comment]
> Also I put find_park_data into park_utils, since I think that makes more sense since that file now exists. What do you think?

I agree. park utils is more general so we can put all the functions related to parks there.

**Review by irinakulinich3712 — DISMISSED** [review]
Works as expected. And I really like the approach used for storing the chosen park name

**Review by AniSanikidze — DISMISSED** [review]
Everything is done perfectly, as always! I agree with Iryna, storing park name this way is a very good approach.

**Review by AniSanikidze — APPROVED** [review]

**Review by irinakulinich3712 — APPROVED** [review]

**Pull request merged**
