### PR TITLE
025 comparing input key

### PR DESCRIPTION
**Pull request by AniSanikidze**
The identifying-keyword function iterates through the map of synonyms. If the match between user input and the synonym is found then it prints the first element of the vector. The first element of the vector is the keyword in all the vectors. So this way it identifies the main keyword. Currently, the println function is used to print the matched keywords, however, in the future, instead of println we can have an actual function there which will take the matched keyword as an argument (Iryna already has that function) and output the reply.

### CODE REVIEW

**Comment by irinakulinich3712** [comment]
Hey, you can already update the function with the "find-park-data" function from 028 branch

**Comment by adzai** [comment]
What's the status of this PR? I still see the data files, some of which are outdated. However, I believe that you are still working on the comparison-key-input.clj file.

**Comment by AniSanikidze** [comment]
> What's the status of this PR? I still see the data files, some of which are outdated. However, I believe that you are still working on the comparison-key-input.clj file.

Yes, you see the data files because of my mistake. When I created this branch, unfortunately, I didn't make sure that it was even with the main branch. I think I need to rebase it.  Or should I delete this branch and create the new one just for the comparison function?

Also, I updated the comparison-key-input.clj file with the whole code, for you, just to see how everything worked. But then I realized it was too unorganized that way, so I left only updated comparison functions in the comparison-key-input.clj file and created separate branches for each issue.

**Comment by adzai** [comment]
I would just make a new one...

**Comment by adzai** [comment]
Moved to #42

**Pull request closed without merging**
